server:
  port: 8989
spring:
  datasource:
    username: root
    password: root
    url: jdbc:h2:mem:dbtest
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
